# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This file is generated by device/infinix/x603/setup-makefiles.sh

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/bin,system/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/etc,system/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/lib,system/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/lib64,system/lib64)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/framework,system/framework)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/bin,system/vendor/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/framework,system/vendor/framework)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/media,system/vendor/media)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/operator,system/vendor/operator)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/plugin,system/vendor/plugin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/priv-app,system/vendor/priv-app)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/res,system/vendor/res)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/app,system/vendor/app)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/etc,system/vendor/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/thh,system/vendor/thh)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/firmware,system/vendor/firmware)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/lib,system/vendor/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/infinix/x603/proprietary/vendor/lib64,system/vendor/lib64)
